// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/apps/measurement-pricer": {
    params: {};
  };
  "/apps/measurement-pricer/validate-price": {
    params: {};
  };
  "/apps/measurement-pricer/buy-now": {
    params: {};
  };
  "/apps/measurement-pricer/config": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/products": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/apps/measurement-pricer" | "/apps/measurement-pricer/validate-price" | "/apps/measurement-pricer/buy-now" | "/apps/measurement-pricer/config" | "/auth/login" | "/auth/*" | "/app" | "/app/additional" | "/app/products" | "/app/rules";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/apps.measurement-pricer.jsx": {
    id: "routes/apps.measurement-pricer";
    page: "/apps/measurement-pricer" | "/apps/measurement-pricer/validate-price" | "/apps/measurement-pricer/buy-now" | "/apps/measurement-pricer/config";
  };
  "routes/apps.measurement-pricer.validate-price.jsx": {
    id: "routes/apps.measurement-pricer.validate-price";
    page: "/apps/measurement-pricer/validate-price";
  };
  "routes/apps.measurement-pricer.buy-now.jsx": {
    id: "routes/apps.measurement-pricer.buy-now";
    page: "/apps/measurement-pricer/buy-now";
  };
  "routes/apps.measurement-pricer.config.jsx": {
    id: "routes/apps.measurement-pricer.config";
    page: "/apps/measurement-pricer/config";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/additional" | "/app/products" | "/app/rules";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.products.jsx": {
    id: "routes/app.products";
    page: "/app/products";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.rules.jsx": {
    id: "routes/app.rules";
    page: "/app/rules";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/apps.measurement-pricer": typeof import("./app/routes/apps.measurement-pricer.jsx");
  "routes/apps.measurement-pricer.validate-price": typeof import("./app/routes/apps.measurement-pricer.validate-price.jsx");
  "routes/apps.measurement-pricer.buy-now": typeof import("./app/routes/apps.measurement-pricer.buy-now.jsx");
  "routes/apps.measurement-pricer.config": typeof import("./app/routes/apps.measurement-pricer.config.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.products": typeof import("./app/routes/app.products.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.rules": typeof import("./app/routes/app.rules.jsx");
};